qos_profiles:
  realtime_sample:
    reliability: best_effort
    congestion_control: drop
    priority: realtime

  config_command:
    reliability: reliable
    congestion_control: block
    priority: interactive_high

  health:
    reliability: best_effort
    congestion_control: drop
    priority: data
